### ISSUE TITLE
Incompatible with simple-rest package

### ISSUE THREAD

**Issue by roberto-naharro** [Urigo/meteor-rxjs#11]
I have the following error trying to create a observable collection:
```
W20161005-08:40:54.003(-5)? (STDERR) Error: Must pass options before Method is defined: /users/insert
W20161005-08:40:54.003(-5)? (STDERR)     at Object.SimpleRest.setMethodOptions (packages/simple_rest/rest.js:25:1)
W20161005-08:40:54.004(-5)? (STDERR)     at Object.Meteor.method (packages/simple_rest/rest.js:99:1)
W20161005-08:40:54.004(-5)? (STDERR)     at packages/simple_rest/rest.js:180:1
W20161005-08:40:54.004(-5)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20161005-08:40:54.007(-5)? (STDERR)     at Server.Meteor.methods.Object.getPrototypeOf.methods [as methods] (packages/simple_rest/rest.js:179:1)
W20161005-08:40:54.007(-5)? (STDERR)     at packages/allow-deny/allow-deny.js:202:22
W20161005-08:40:54.007(-5)? (STDERR)     at [object Object].CollectionPrototype._defineMutationMethods (packages/allow-deny/allow-deny.js:108:84)
W20161005-08:40:54.008(-5)? (STDERR)     at [object Object].Mongo.Collection._defineMutationMethods (packages/simple_rest/rest.js:173:1)
W20161005-08:40:54.008(-5)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:240:12)
W20161005-08:40:54.008(-5)? (STDERR)     at new Collection (/node_modules/meteor-rxjs/dist/ObservableCollection.js:14:36)
```

I thinks it's related to [simple-rest](https://atmospherejs.com/simple/rest) meteor package:

https://github.com/stubailo/meteor-rest/blob/devel/packages/rest/rest.js#L25

**Comment by barbatus** [comment]
So how do you use it?

**Comment by roberto-naharro** [comment]
I want to create a REST API, and, at the same time, have a Mongo observable collection working with my angular2-meteor project. But it seems, at the moment you define a new mongo observable collection, it fails... I will do some test in next days and put more info and code

**Comment by roberto-naharro** [comment]
I have done some test and it seems there was an error in my code. It's working fine now. I will do more test, and in case of having any problem, I will open this thread again. Thanks!
